### ISSUE TITLE
Denied again

### ISSUE THREAD

**Issue by zerebos** [nicola02nb/BetterDiscord-Stuff#2]
Currently the plugin polls the status every 5 seconds (or 1) which can get potentially spammy, can you try using the internal events to trigger when to check or update status? You can easily subscribe to the same internal stores being used here.

**Comment by zerebos** [comment]
This is about AutoSwitchStatus btw. On a more personal note the plugin name is a little confusing based on its limited focus, but I don't have a better suggestion lol

**Comment by nicola02nb** [comment]
> ntly the plugin polls the status every 5 seconds (or 1) which can get potentially spammy, can you try using the internal events to trigger when to check or update status? You can easily subscribe to the same internal stores being used here.

I'm releasing one with internal events soon, I have to to tweak a few things and I'll publish it

**Comment by nicola02nb** [comment]
All done fixed both plugins
